RD = config["result_dir"]

# Check the config file for the BAM setting
GENERATE_BAM = config.get("generate_bam", True)
# Check the config file for UMI dedup
UMIS_DEDUP = config.get("UMIs_dedup", True)

rule starsolo:
    input:
        r1        = config["lane_r1"],
        r2        = config["lane_r2"],
        whitelist = RD + "/starsolo/whitelist.txt",
        genome    = config["star_genome_dir"],
        gtf       = config["gtf"]
    output:
        matrix   = RD + "/starsolo/Solo.out/Gene/raw/matrix.mtx",
        barcodes = RD + "/starsolo/Solo.out/Gene/raw/barcodes.tsv",
        features = RD + "/starsolo/Solo.out/Gene/raw/features.tsv",
        star_log = RD + "/starsolo/Log.final.out",
        star_summary = RD + "/starsolo/Solo.out/Gene/Summary.csv",
        # Conditionally require the BAM file as an output
        bam      = [RD + "/bams/Aligned.sortedByCoord.out.bam"] if GENERATE_BAM else []
    params:
        prefix   = RD + "/starsolo/",
        bam_dir  = RD + "/bams/",
        cb_len   = config["barcode_len"],
        umi_len  = config["umi_len"],
        
        # Determine UMI dedup argument based on config
        umi_dedup_arg = "1MM_Directional" if UMIS_DEDUP else "NoDedup",

        # Convert Python boolean to a string to use in bash
        make_bam = "True" if GENERATE_BAM else "False",
        
        # Dynamically build the BAM arguments for the STAR command
        bam_args = lambda wildcards, threads: (
            f"--outSAMtype BAM SortedByCoordinate "
            f"--outSAMattributes NH HI AS NM CR UR CB UB GX GN sS sQ sM "
            f"--limitBAMsortRAM 27112659435 "
            f"--outBAMsortingThreadN {threads}"
        ) if GENERATE_BAM else "--outSAMtype None"
        
    log:
        RD + "/logs/starsolo/starsolo.log"
    benchmark:
        RD + "/benchmarks/starsolo/starsolo.tsv"
    retries: 3
    resources:
        mem_mb = lambda wildcards, attempt: 50000 + ((attempt - 1) * 100000),
        runtime = lambda wildcards, attempt: 720 + ((attempt - 1) * 1440)
    threads:
        config["threads"]["star"]
    container:
        config["containers"]["star"]
    shell:
        """
        umi_start=$(( {params.cb_len} + 1 ))

        STAR \
            --runMode alignReads \
            --runThreadN {threads} \
            --genomeDir {input.genome} \
            --sjdbGTFfile {input.gtf} \
            --readFilesIn {input.r2} {input.r1} \
            --readFilesCommand zcat \
            --soloType CB_UMI_Simple \
            --soloCBwhitelist {input.whitelist} \
            --soloCBstart 1 --soloCBlen {params.cb_len} \
            --soloUMIstart $umi_start --soloUMIlen {params.umi_len} \
            --clipAdapterType CellRanger4 \
            --soloFeatures Gene \
            --soloUMIdedup {params.umi_dedup_arg} \
            --soloBarcodeReadLength 0 \
            --soloCellFilter None \
            --outFileNamePrefix {params.prefix} \
            {params.bam_args} \
        > {log} 2>&1

        # Only move the BAM file if we actually told STAR to create it
        if [ "{params.make_bam}" == "True" ]; then
            mv {params.prefix}Aligned.sortedByCoord.out.bam {params.bam_dir}
        fi
        """

rule samtools_index:
    input:
        RD + "/bams/Aligned.sortedByCoord.out.bam"
    output:
        RD + "/bams/Aligned.sortedByCoord.out.bam.bai"
    log:
        RD + "/logs/samtools_index/samtools_index.log"
    benchmark:
        RD + "/benchmarks/samtools_index/samtools_index.tsv"
    container:
        config["containers"]["samtools"]
    shell:
        "samtools index {input} > {log} 2>&1"

rule split_bams_by_sample:
    input:
        bam = RD + "/bams/Aligned.sortedByCoord.out.bam",
        bai = RD + "/bams/Aligned.sortedByCoord.out.bam.bai", # Ensure it's indexed first
        barcode_map = RD + "/starsolo/barcode_to_sample.tsv"  # Generated by prepare_inputs.smk
    output:
        split_dir = directory(RD + "/bams/split_by_sample")
    log:
        RD + "/logs/samtools_split/samtools_split.log"
    benchmark:
        RD + "/benchmarks/samtools_split/samtools_split.tsv"
    threads: 
        8
    resources:
        mem_mb = 32000,
        runtime = 240
    container:
        config["containers"]["samtools"]
    shell:
        """
        echo "Splitting massive BAM file by Cell Barcode (CB)..." > {log}
        
        # Split BAM by CB tag
        samtools split -@ {threads} -d CB \
            -f "{output.split_dir}/%!.bam" \
            {input.bam} >> {log} 2>&1
            
        echo "Renaming BAMs to sample names..." >> {log}
        
        # Loop through the map file
        while IFS=$'\\t' read -r barcode sample rest; do
            # Skip empty lines or header row (adjust "barcode" if your header is capitalized differently)
            if [[ -z "$barcode" || "$barcode" =~ ^[Bb]arcode ]]; then continue; fi
            
            src="{output.split_dir}/$barcode.bam"
            dest="{output.split_dir}/$sample.bam"
            
            # If a sample had reads, its sequence BAM exists; rename and index it
            if [[ -f "$src" ]]; then
                mv "$src" "$dest"
                samtools index -@ 2 "$dest"
            fi
        done < {input.barcode_map}
        
        # Rename the "unassigned" file so it makes sense (reads missing the CB tag)
        if [[ -f "{output.split_dir}/-.bam" ]]; then
            mv "{output.split_dir}/-.bam" "{output.split_dir}/Unassigned_Reads.bam"
            samtools index -@ 2 "{output.split_dir}/Unassigned_Reads.bam"
        fi
        
        echo "Done!" >> {log}
        """